# Generated by Django 5.2.15 on 2026-07-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='tipo_accion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='url_accion',
            field=models.URLField(blank=True, null=True),
        ),
    ]
