# Generated by Django 5.2.15 on 2026-06-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membresias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membresia',
            name='pases_restantes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='planmembresia',
            name='pases_incluidos',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
