# Generated by Django 5.2.15 on 2026-06-29 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membresias', '0002_membresia_pases_restantes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membresia',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
