# Generated by Django 5.2.15 on 2026-07-12 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membresias', '0003_alter_membresia_fecha_fin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membresia',
            name='fecha_fin',
        ),
    ]
