# Generated by Django 5.2.15 on 2026-07-17 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membresias', '0004_remove_membresia_fecha_fin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planmembresia',
            name='duracion_dias',
        ),
    ]
