# Generated by Django 5.2.15 on 2026-06-17 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membresias', '0002_membresia_pases_restantes_and_more'),
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='membresia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='membresias.membresia'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tipo_transaccion',
            field=models.CharField(choices=[('recarga', 'Recarga'), ('pago_peaje', 'Pago de peaje'), ('uso_membresia', 'Uso de membresía'), ('devolucion', 'Devolución')], max_length=20),
        ),
    ]
