# Generated by Django 5.2.15 on 2026-06-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_transaccion_membresia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='tipo_transaccion',
            field=models.CharField(choices=[('recarga', 'Recarga'), ('pago_peaje', 'Pago de peaje'), ('compra_membresia', 'Compra de membresía'), ('uso_membresia', 'Uso de membresía'), ('devolucion', 'Devolución')], max_length=20),
        ),
    ]
