# Generated by Django 5.2.15 on 2026-07-16 00:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_alter_transaccion_tipo_transaccion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TarjetaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, max_length=80, null=True)),
                ('titular', models.CharField(max_length=120)),
                ('marca', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('amex', 'American Express'), ('diners', 'Diners Club'), ('desconocida', 'Desconocida')], default='desconocida', max_length=30)),
                ('ultimos4', models.CharField(max_length=4)),
                ('mes_expiracion', models.PositiveSmallIntegerField()),
                ('anio_expiracion', models.PositiveSmallIntegerField()),
                ('token_simulado', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('principal', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas_bancarias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarjeta bancaria',
                'verbose_name_plural': 'Tarjetas bancarias',
                'ordering': ['-principal', '-fecha_creacion'],
            },
        ),
    ]
