# Generated by Django 5.2.15 on 2026-07-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0004_tarjetabancaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('fallida', 'Fallida'), ('anulada', 'Anulada')], default='pendiente', max_length=20),
        ),
    ]
