# Generated by Django 5.2.15 on 2026-06-16 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('peajes', '0001_initial'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisoVehiculoRobado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_denuncia', models.CharField(blank=True, max_length=100, null=True)),
                ('entidad_denuncia', models.CharField(blank=True, max_length=120, null=True)),
                ('fecha_denuncia', models.DateField(blank=True, null=True)),
                ('fecha_aviso', models.DateTimeField(auto_now_add=True)),
                ('lugar_robo', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('latitud_robo', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud_robo', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('documento_respaldo', models.FileField(blank=True, null=True, upload_to='documentos_denuncia/')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('detectado', 'Detectado'), ('derivado_autoridad', 'Derivado a autoridad'), ('cerrado', 'Cerrado'), ('cancelado', 'Cancelado')], default='activo', max_length=30)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos_robo', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Aviso de vehículo robado',
                'verbose_name_plural': 'Avisos de vehículos robados',
                'ordering': ['-fecha_aviso'],
            },
        ),
        migrations.CreateModel(
            name='AlertaSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(default='Vehículo con aviso interno de robo', max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('validada', 'Validada por operador'), ('derivada', 'Derivada a autoridad'), ('atendida', 'Atendida'), ('descartada', 'Descartada')], default='pendiente', max_length=30)),
                ('latitud_deteccion', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud_deteccion', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('paso_peaje', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerta_seguridad', to='peajes.pasopeaje')),
                ('peaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_seguridad', to='peajes.peaje')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_seguridad', to='vehiculos.vehiculo')),
                ('aviso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='seguridad.avisovehiculorobado')),
            ],
            options={
                'verbose_name': 'Alerta de seguridad',
                'verbose_name_plural': 'Alertas de seguridad',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='UbicacionDeteccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('direccion_referencial', models.CharField(blank=True, max_length=255, null=True)),
                ('url_maps', models.URLField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('alerta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ubicacion', to='seguridad.alertaseguridad')),
                ('peaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones_deteccion', to='peajes.peaje')),
            ],
            options={
                'verbose_name': 'Ubicación de detección',
                'verbose_name_plural': 'Ubicaciones de detección',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
