# Generated by Django 5.2.15 on 2026-06-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertaseguridad',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('revisada', 'Revisada'), ('derivada', 'Derivada a autoridad'), ('cerrada', 'Cerrada'), ('descartada', 'Descartada')], default='pendiente', max_length=30),
        ),
        migrations.AlterField(
            model_name='avisovehiculorobado',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('detectado', 'Detectado'), ('cerrado', 'Cerrado'), ('cancelado', 'Cancelado')], default='activo', max_length=20),
        ),
    ]
