# Generated by Django 5.2.15 on 2026-07-17 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_alter_alertaseguridad_estado_and_more'),
        ('vehiculos', '0005_alter_categoriavehiculo_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudReactivacionVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('documento_respaldo', models.FileField(blank=True, null=True, upload_to='seguridad/reactivaciones/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('respuesta_admin', models.TextField(blank=True, null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('aviso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_reactivacion', to='seguridad.avisovehiculorobado')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_reactivacion_revisadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_reactivacion_vehiculo', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_reactivacion', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Solicitud de reactivación de vehículo',
                'verbose_name_plural': 'Solicitudes de reactivación de vehículos',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
