# Generated by Django 5.2.15 on 2026-07-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0003_solicitudreactivacionvehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avisovehiculorobado',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('detectado', 'Detectado'), ('recuperado', 'Recuperado'), ('cerrado', 'Cerrado'), ('cancelado', 'Cancelado')], default='activo', max_length=20),
        ),
    ]
