# Generated by Django 5.2.15 on 2026-06-16 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('ubicacion', models.CharField(max_length=150)),
                ('tipo_camara', models.CharField(blank=True, max_length=80, null=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva'), ('mantenimiento', 'Mantenimiento')], default='activa', max_length=20)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cámara',
                'verbose_name_plural': 'Cámaras',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Peaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('ciudad', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=255)),
                ('latitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('tarifa', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('mantenimiento', 'Mantenimiento')], default='activo', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Peaje',
                'verbose_name_plural': 'Peajes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PasoPeaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa_detectada', models.CharField(max_length=15)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('exonerado', 'Exonerado'), ('fallido', 'Fallido')], default='pendiente', max_length=20)),
                ('estado_seguridad', models.CharField(choices=[('normal', 'Normal'), ('alerta', 'Alerta'), ('revision', 'Revisión')], default='normal', max_length=20)),
                ('imagen_capturada', models.ImageField(blank=True, null=True, upload_to='capturas_placas/')),
                ('observacion', models.TextField(blank=True, null=True)),
                ('camara', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capturas', to='peajes.camara')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pasos_peaje', to='vehiculos.vehiculo')),
                ('peaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='peajes.peaje')),
            ],
            options={
                'verbose_name': 'Paso por peaje',
                'verbose_name_plural': 'Pasos por peaje',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.AddField(
            model_name='camara',
            name='peaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camaras', to='peajes.peaje'),
        ),
    ]
