# Generated by Django 5.2.15 on 2026-06-17 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membresias', '0002_membresia_pases_restantes_and_more'),
        ('peajes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasopeaje',
            name='membresia_utilizada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pasos_peaje', to='membresias.membresia'),
        ),
        migrations.AddField(
            model_name='pasopeaje',
            name='tarifa_aplicada',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='pasopeaje',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('membresia', 'Membresía'), ('exonerado', 'Exonerado'), ('fallido', 'Fallido')], default='pendiente', max_length=20),
        ),
    ]
