# Generated by Django 5.2.15 on 2026-06-22 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peajes', '0002_pasopeaje_membresia_utilizada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camara',
            name='procesar_anpr',
            field=models.BooleanField(default=True, help_text='Indica si esta camara sera usada para detenccion automatica de placas.'),
        ),
        migrations.AddField(
            model_name='camara',
            name='stream_url',
            field=models.URLField(blank=True, help_text='URL RTSP, HTTP, indice de webcam o ruta de video.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='camara',
            name='tipo_fuente',
            field=models.CharField(choices=[('rtsp', 'RTSP / Camara IP'), ('http', 'HTTP / MJPEG'), ('usb', 'Webcam USB'), ('video', 'Archivo de video')], default='rtsp', max_length=20),
        ),
    ]
