# Generated by Django 5.2.15 on 2026-07-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peajes', '0003_camara_procesar_anpr_camara_stream_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peaje',
            name='latitud',
            field=models.DecimalField(decimal_places=20, max_digits=20),
        ),
        migrations.AlterField(
            model_name='peaje',
            name='longitud',
            field=models.DecimalField(decimal_places=20, max_digits=20),
        ),
    ]
