# Generated by Django 5.2.15 on 2026-07-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peajes', '0005_alter_peaje_latitud_alter_peaje_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peaje',
            name='latitud',
            field=models.DecimalField(decimal_places=20, max_digits=50),
        ),
        migrations.AlterField(
            model_name='peaje',
            name='longitud',
            field=models.DecimalField(decimal_places=20, max_digits=50),
        ),
    ]
