# Generated by Django 5.2.15 on 2026-07-15 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peajes', '0006_alter_peaje_latitud_alter_peaje_longitud'),
        ('vehiculos', '0005_alter_categoriavehiculo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peaje',
            name='tarifa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.CreateModel(
            name='TarifaPeajeCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifas_por_peaje', to='vehiculos.categoriavehiculo')),
                ('peaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas_categoria', to='peajes.peaje')),
            ],
            options={
                'verbose_name': 'Tarifa por peaje y categoría',
                'verbose_name_plural': 'Tarifas por peaje y categoría',
                'ordering': ['peaje__nombre', 'categoria__numero_ejes', 'valor'],
                'unique_together': {('peaje', 'categoria')},
            },
        ),
    ]
