# Generated by Django 5.2.15 on 2026-07-15 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peajes', '0007_alter_peaje_tarifa_tarifapeajecategoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViaConcesionada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tiempo_validez_minutos', models.PositiveIntegerField(default=120, help_text='Tiempo durante el cual un pago previo permite pasar por otros peajes de la misma vía.')),
                ('cobro_unico_por_trayecto', models.BooleanField(default=True, help_text='Si está activo, un pago previo exonera otros peajes de la misma vía dentro del tiempo definido.')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Vía concesionada',
                'verbose_name_plural': 'Vías concesionadas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='peaje',
            name='orden_en_via',
            field=models.PositiveIntegerField(default=0, help_text='Orden del peaje dentro de la vía concesionada.'),
        ),
        migrations.AddField(
            model_name='peaje',
            name='via_concesionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peajes', to='peajes.viaconcesionada'),
        ),
    ]
