# Generated by Django 5.2.15 on 2026-07-15 21:41

from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('peajes', '0008_viaconcesionada_peaje_orden_en_via_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaconcesionada',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='viaconcesionada',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
