# Generated by Django 5.2.15 on 2026-07-18 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peajes', '0009_viaconcesionada_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camara',
            name='stream_url',
            field=models.CharField(blank=True, help_text='URL RTSP, HTTP, índice de webcam USB o ruta de video.', max_length=500, null=True),
        ),
    ]
