# Generated by Django 5.2.15 on 2026-06-17 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('liviando', 'Liviano'), ('pesado', 'Pesado'), ('extrapesado', 'Extrapesado')], max_length=20)),
                ('numero_ejes', models.PositiveIntegerField()),
                ('tarifa', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría de Vehículo',
                'verbose_name_plural': 'Categorías de Vehículos',
                'ordering': ['numero_ejes', 'tarifa'],
            },
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='vehiculos.categoriavehiculo'),
        ),
    ]
