# Generated by Django 5.2.15 on 2026-06-29 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_categoriavehiculo_vehiculo_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='estado_revision',
            field=models.CharField(choices=[('en_revision', 'En revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='en_revision', max_length=20),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='fecha_revision',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='motivo_revision',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos_revisados', to=settings.AUTH_USER_MODEL),
        ),
    ]
