# Generated by Django 5.2.15 on 2026-06-29 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0003_vehiculo_estado_revision_vehiculo_fecha_revision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='documento_respaldo',
            field=models.FileField(blank=True, null=True, upload_to='vehiculos/documentos/'),
        ),
    ]
