# Generated by Django 5.2.15 on 2026-07-07 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0004_vehiculo_documento_respaldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriavehiculo',
            name='tipo',
            field=models.CharField(choices=[('liviano', 'Liviano'), ('pesado', 'Pesado'), ('extrapesado', 'Extrapesado')], max_length=20),
        ),
    ]
